name: Changelog CI

on:
  push:
    branches:
      - feature/change-log
  pull_request_target:
    branches:
      - main

jobs:
  Change-log:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup golang
        uses: WillAbides/setup-go-faster@v1.7.0
        with:
          go-version: '1.18.1'
      - name: Install git-chglog
        run: go install github.com/git-chglog/git-chglog/cmd/git-chglog@latest
      - name: Show tag
        run: git tag -l
      - name: Show log
        run: git log
      - name: Gen changelog
        run: git-chglog -o CHANGELOG.md
      - name: Git push
        run: git status -s |
          git add . |
          git commit -m "docs(changelog):generating change logs" |
          git push -u
