name: Changelog CI

on:
  push:
    branches:
      - *
  pull_request_target:
    branches:
      - main

jobs:
  Change-log:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Git version
        run: git --version
